### ISSUE TITLE
Tensorflow error and not able to watch progress with tensorboard

### ISSUE THREAD

**Issue by sunsibar** [jesbu1/hidio#4]
The following command: 

`python -m alf.bin.train --gin_file hierarchical_pusher.gin --root_dir=LOG_DIR`

Gives me the following error:

```
W1117 20:23:55.725374 140132368676672 common.py:712] last_kernel_initializer is not specified for the last layer of size 8.
I1117 20:23:55.769429 140132368676672 sac_algorithm.py:79] Target entropy is calculated for Lower_level_SAC: -6.414035109786505.
||||||||||||||||||||||||||||||//hidio/alf/alf/utils/checkpoint_utils.py:94: UserWarning: Checkpoint 'latest' does not exist. Train from scratch.
  global_step)))
I1117 20:08:22.878117 140049263687488 policy_trainer.py:234] ['hierarchical_pusher.gin'] -> ['LOG_DIR']: 3 time=2.017 throughput=0.00
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File ||||||||||||||||||||||||||||||/lib/python3.7/site-packages/tensorboard/summary/writer/event_file_writer.py", line 211, in run
    self._record_writer.write(data)
  File "||||||||||||||||||||||||||||||/lib/python3.7/site-packages/tensorboard/summary/writer/record_writer.py", line 39, in write
    self._writer.write(header + header_crc + data + footer_crc)
  File "||||||||||||||||||||||||||||||lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 507, in write
    self.fs.append(self.filename, file_content, self.binary_mode)
  File "||||||||||||||||||||||||||||||lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 150, in append
    self._write(filename, file_content, "ab" if binary_mode else "a")
  File "||||||||||||||||||||||||||||||/lib/python3.7/site-packages/tensorboard/compat/tensorflow_stub/io/gfile.py", line 154, in _write
    with io.open(filename, mode, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: b'LOG_DIR/train/events.out.tfevents.1637172500.[computer name]-2.6446.1'

```
The directory LOG_DIR exists, I'm removing everything from it before running the command. Also, the file it does not find is actually created, I don't know if before or after the error is thrown.   
It seems to try to restart from a checkpoint. Can I pass a parameter so that it knows to start from scratch?  

Afterwards, the code continues to run, but does not give any output (so probably has gotten stuck). Also, trying to run tensorboard --logdir LOG_DIR/train gives another error:      

```
TensorFlow installation not found - running with reduced feature set.
Traceback (most recent call last):
  File "||||||||||||||||||||||||||||||/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "||||||||||||||||||||||||||||||lib/python3.7/site-packages/tensorboard/main.py", line 66, in run_main
    app.run(tensorboard.main, flags_parser=tensorboard.configure)
  File "||||||||||||||||||||||||||||||/lib/python3.7/site-packages/absl/app.py", line 306, in run
    flags_parser,
  File "/||||||||||||||||||||||||||||||lib/python3.7/site-packages/absl/app.py", line 375, in _run_init
    flags_parser=flags_parser,
  File "/||||||||||||||||||||||||||||||lib/python3.7/site-packages/absl/app.py", line 220, in _register_and_parse_flags_with_usage
    args_to_main = flags_parser(original_argv)
  File "||||||||||||||||||||||||||||||/lib/python3.7/site-packages/tensorboard/program.py", line 215, in configure
    flags = base_parser.parse_args(argv[1:])  # Strip binary name from argv.
  File "/usr/lib/python3.7/argparse.py", line 1754, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "||||||||||||||||||||||||||||||/lib/python3.7/site-packages/absl/flags/argparse_flags.py", line 169, in parse_known_args
    args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 1786, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python3.7/argparse.py", line 2021, in _parse_known_args
    ', '.join(required_actions))
TypeError: sequence item 0: expected str instance, NoneType found
```

Any help is appreciated.
----------------------------------------------------

Python version: **3.7**
MuJoCo version: Tested with both installing from the repository, and with  2.0.2.13 (the version given in your readme).

**Comment by hnyu** [comment]
Hi @sunsibar , what is the version of your tensorboard? It seems like a tensorboard issue to me

**Comment by sunsibar** [comment]
Aha, yes that seems right! It also throws the error when I ask it for its version only.
However, when I upgrade tensorboard it complains that alf needs an earlier version, and after downgrading to that version, I get the previous error.   
I'll try around a bit more and see if I can make it work

**Comment by hnyu** [comment]
Maybe this issue is related? https://github.com/jesbu1/hidio/issues/2

**Comment by sunsibar** [comment]
Edit: yes, that issue seems very related, wow sorry for not seeing that! Seems to be the same problem. I'm also installing tensorflow now ^^" Thanks!

**Comment by hnyu** [comment]
> Edit: yes, that issue seems very related, wow sorry for not seeing that! Seems to be the same problem. I'm also installing tensorflow now ^^" Thanks!

No problem. Just checked and realized that HIDIO uses an old version (def59fe) of ALF. For this version, its setup.py indeed requires 2.1.0. I guess you can try upgrading it or installing tensorflow==2.1.0.

**Comment by sunsibar** [comment]
It works! Installing tensorflow==2.1.0 was what did the trick. Thank you very much!
